### ISSUE TITLE
"Application Error" net::ERR_INSUFFICIENT_RESOURCES

### ISSUE THREAD

**Issue by ariejan** [kabisa/kudos-frontend#61]
Completely uninstalled and reinstalled the android app. It seems to log me in directly (which is strange), I logout, the login screen is messed up. Any subsequent try to start the app results in this error.

![2019-04-01 10 59 29](https://user-images.githubusercontent.com/1913/55318349-df3f8e00-5472-11e9-844f-c6a6e2ea3fb0.jpg)

**Comment by MeijerM1** [comment]
Closed because it's no longer relevant.
